import { Months } from "./types";

export const defaultPhoneCode = "+1";
export const BASE_API_URL =
  process.env.NEXT_PUBLIC_BASE_API_URL?.trim() ||
  // "http://localhost:4001" ||
  "http://13.50.165.77/apiTaxipro";

export const BASE_APP_URL =
  process.env.NEXT_PUBLIC_BASE_APP_URL?.trim() ||
  // "http://localhost:3000" ||
  "http://13.50.165.77";

export const emailRegex =
  /^(([^\s"(),.:;<>@[\\\]]+(\.[^\s"(),.:;<>@[\\\]]+)*)|(".+"))@((\[(?:\d{1,3}\.){3}\d{1,3}])|(([\dA-Za-z-]+\.)+[A-Za-z]{2,}))$/;
export const invalidEmailFormat = "Please Enter Valid Email Address";
export const strongPasswordRegex =
  /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\$%\^&\*]).{8,}$/;

export const dateFormat = "YYYY/MM/DD";

export const dateTimeFormat = "DD/MM/YYYY HH:mm:ss";

export const PAGE_LIMIT = 10;

export const passwordLenRegex = /^.{8,35}$/;
export const passwordUpperCaseRegex = /[A-Z]/;
export const passwordLowerCaseRegex = /[a-z]/;
export const passwordSpecialCharRegex = /[#?!@$%^&*-]/;

export const privateBucketName =
  process.env.NEXT_PRIVATE_BUCKET_NAME || "gynCoachPro-private";

export const monthOptions = Object.values(Months).map((item) => ({
  label: item,
  value: item,
}));
export const monthsMap = Object.entries(Months).map(([key, value]) => ({
  key,
  value,
}));

export const employmentStatusOptions = [
  { label: "Tillsvidareanställning", value: "Tillsvidareanställning" },
  { label: "Provanställning", value: "Provanställning" },
  { label: "Behovsanställning", value: "Behovsanställning" },
  { label: "Tidsbegränsad anställning", value: "Tidsbegränsad anställning" },
];

export const vehicleTypeOptions = [
  { label: "Benzine", value: "Benzine" },
  { label: "Diesel", value: "Diesel" },
  { label: "El", value: "El" },
  { label: "Hybrid", value: "Hybrid" },
  { label: "Other", value: "Other" },
];

export const employmentTypeOptions = [
  { label: "Heltid", value: "Heltid" },
  { label: "Deltid", value: "Deltid" },
  { label: "Varierande", value: "Varierande" },
];
export const employmentTypeVariableTimeOptions = [
  { label: "Helg", value: "Helg" },
  { label: "Kväll", value: "Kväll" },
  { label: "ensam", value: "ensam" },
  { label: "dag", value: "dag" },
];

export const workingTimeOptions = [
  // { label: "Alla", value: "Alla" },
  { label: "Ensam", value: "Ensam" },
  { label: "Heltid", value: "Heltid" },
  { label: "Deltid", value: "Deltid" },
  { label: "Helg", value: "Helg" },
  { label: "Dag", value: "Dag" },
  { label: "Kväll", value: "Kväll" },
];

export const kommuneOptions = [
  { label: "Ale", value: "Ale" },
  { label: "Alingsås", value: "Alingsås" },
  { label: "Alvesta", value: "Alvesta" },
  { label: "Aneby", value: "Aneby" },
  { label: "Arboga", value: "Arboga" },
  { label: "Arjeplog", value: "Arjeplog" },
  { label: "Arvidsjaur", value: "Arvidsjaur" },
  { label: "Arvika", value: "Arvika" },
  { label: "Askersund", value: "Askersund" },
  { label: "Avesta", value: "Avesta" },
  { label: "Bengtsfors", value: "Bengtsfors" },
  { label: "Berg", value: "Berg" },
  { label: "Bjurholm", value: "Bjurholm" },
  { label: "Bjuv", value: "Bjuv" },
  { label: "Boden", value: "Boden" },
  { label: "Bollebygd", value: "Bollebygd" },
  { label: "Bollnäs", value: "Bollnäs" },
  { label: "Borgholm", value: "Borgholm" },
  { label: "Borlänge", value: "Borlänge" },
  { label: "Borås", value: "Borås" },
  { label: "Botkyrka", value: "Botkyrka" },
  { label: "Boxholm", value: "Boxholm" },
  { label: "Bromölla", value: "Bromölla" },
  { label: "Bräcke", value: "Bräcke" },
  { label: "Burlöv", value: "Burlöv" },
  { label: "Dals-Ed", value: "Dals-Ed" },
  { label: "Danderyd", value: "Danderyd" },
  { label: "Degerfors", value: "Degerfors" },
  { label: "Dorotea", value: "Dorotea" },
  { label: "Eda", value: "Eda" },
  { label: "Ekerö", value: "Ekerö" },
  { label: "Eksjö", value: "Eksjö" },
  { label: "Emmaboda", value: "Emmaboda" },
  { label: "Enköping", value: "Enköping" },
  { label: "Eskilstuna", value: "Eskilstuna" },
  { label: "Eslöv", value: "Eslöv" },
  { label: "Essunga", value: "Essunga" },
  { label: "Fagersta", value: "Fagersta" },
  { label: "Falkenberg", value: "Falkenberg" },
  { label: "Falköping", value: "Falköping" },
  { label: "Falun", value: "Falun" },
  { label: "Filipstad", value: "Filipstad" },
  { label: "Finspång", value: "Finspång" },
  { label: "Flen", value: "Flen" },
  { label: "Forshaga", value: "Forshaga" },
  { label: "Färgelanda", value: "Färgelanda" },
  { label: "Gagnef", value: "Gagnef" },
  { label: "Gislaved", value: "Gislaved" },
  { label: "Gnesta", value: "Gnesta" },
  { label: "Gnosjö", value: "Gnosjö" },
  { label: "Gotland", value: "Gotland" },
  { label: "Grums", value: "Grums" },
  { label: "Grästorp", value: "Grästorp" },
  { label: "Gullspång", value: "Gullspång" },
  { label: "Gällivare", value: "Gällivare" },
  { label: "Gävle", value: "Gävle" },
  { label: "Göteborg", value: "Göteborg" },
  { label: "Göteborgs Stad", value: "Göteborgs Stad" },
  { label: "Götene", value: "Götene" },
  { label: "Habo", value: "Habo" },
  { label: "Hagfors", value: "Hagfors" },
  { label: "Hallsberg", value: "Hallsberg" },
  { label: "Hallstahammar", value: "Hallstahammar" },
  { label: "Halmstad", value: "Halmstad" },
  { label: "Hammarö", value: "Hammarö" },
  { label: "Haninge", value: "Haninge" },
  { label: "Haparanda", value: "Haparanda" },
  { label: "Heby", value: "Heby" },
  { label: "Hedemora", value: "Hedemora" },
  { label: "Helsingborg", value: "Helsingborg" },
  { label: "Herrljunga", value: "Herrljunga" },
  { label: "Hjo", value: "Hjo" },
  { label: "Hofors", value: "Hofors" },
  { label: "Huddinge", value: "Huddinge" },
  { label: "Hudiksvall", value: "Hudiksvall" },
  { label: "Hultsfred", value: "Hultsfred" },
  { label: "Hylte", value: "Hylte" },
  { label: "Håbo", value: "Håbo" },
  { label: "Hällefors", value: "Hällefors" },
  { label: "Härjedalen", value: "Härjedalen" },
  { label: "Härnösand", value: "Härnösand" },
  { label: "Härryda", value: "Härryda" },
  { label: "Hässleholm", value: "Hässleholm" },
  { label: "Höganäs", value: "Höganäs" },
  { label: "Högsby", value: "Högsby" },
  { label: "Hörby", value: "Hörby" },
  { label: "Höör", value: "Höör" },
  { label: "Jokkmokk", value: "Jokkmokk" },
  { label: "Järfälla", value: "Järfälla" },
  { label: "Jönköping", value: "Jönköping" },
  { label: "Kalix", value: "Kalix" },
  { label: "Kalmar", value: "Kalmar" },
  { label: "Karlsborg", value: "Karlsborg" },
  { label: "Karlshamn", value: "Karlshamn" },
  { label: "Karlskoga", value: "Karlskoga" },
  { label: "Karlskrona", value: "Karlskrona" },
  { label: "Karlstad", value: "Karlstad" },
  { label: "Katrineholm", value: "Katrineholm" },
  { label: "Kil", value: "Kil" },
  { label: "Kinda", value: "Kinda" },
  { label: "Kiruna", value: "Kiruna" },
  { label: "Klippan", value: "Klippan" },
  { label: "Knivsta", value: "Knivsta" },
  { label: "Kramfors", value: "Kramfors" },
  { label: "Kristianstad", value: "Kristianstad" },
  { label: "Kristinehamn", value: "Kristinehamn" },
  { label: "Krokom", value: "Krokom" },
  { label: "Kumla", value: "Kumla" },
  { label: "Kungsbacka", value: "Kungsbacka" },
  { label: "Kungsör", value: "Kungsör" },
  { label: "Kungälv", value: "Kungälv" },
  { label: "Kävlinge", value: "Kävlinge" },
  { label: "Köping", value: "Köping" },
  { label: "Laholm", value: "Laholm" },
  { label: "Landskrona", value: "Landskrona" },
  { label: "Laxå", value: "Laxå" },
  { label: "Lekeberg", value: "Lekeberg" },
  { label: "Leksand", value: "Leksand" },
  { label: "Lerum", value: "Lerum" },
  { label: "Lessebo", value: "Lessebo" },
  { label: "Lidingö", value: "Lidingö" },
  { label: "Lidköping", value: "Lidköping" },
  { label: "Lilla Edet", value: "Lilla Edet" },
  { label: "Lindesberg", value: "Lindesberg" },
  { label: "Linköping", value: "Linköping" },
  { label: "Ljungby", value: "Ljungby" },
  { label: "Ljusdal", value: "Ljusdal" },
  { label: "Ljusnarsberg", value: "Ljusnarsberg" },
  { label: "Lomma", value: "Lomma" },
  { label: "Ludvika", value: "Ludvika" },
  { label: "Luleå", value: "Luleå" },
  { label: "Lund", value: "Lund" },
  { label: "Lycksele", value: "Lycksele" },
  { label: "Lysekil", value: "Lysekil" },
  { label: "Malmö", value: "Malmö" },
  { label: "Malung-Sälen", value: "Malung-Sälen" },
  { label: "Malå", value: "Malå" },
  { label: "Mariestad", value: "Mariestad" },
  { label: "Mark", value: "Mark" },
  { label: "Markaryd", value: "Markaryd" },
  { label: "Mellerud", value: "Mellerud" },
  { label: "Mjölby", value: "Mjölby" },
  { label: "Mora", value: "Mora" },
  { label: "Motala", value: "Motala" },
  { label: "Mullsjö", value: "Mullsjö" },
  { label: "Munkedal", value: "Munkedal" },
  { label: "Munkfors", value: "Munkfors" },
  { label: "Mölndal", value: "Mölndal" },
  { label: "Mönsterås", value: "Mönsterås" },
  { label: "Mörbylånga", value: "Mörbylånga" },
  { label: "Nacka", value: "Nacka" },
  { label: "Nora", value: "Nora" },
  { label: "Norberg", value: "Norberg" },
  { label: "Nordanstig", value: "Nordanstig" },
  { label: "Nordmaling", value: "Nordmaling" },
  { label: "Norrköping", value: "Norrköping" },
  { label: "Norrtälje", value: "Norrtälje" },
  { label: "Norsjö", value: "Norsjö" },
  { label: "Nybro", value: "Nybro" },
  { label: "Nykvarn", value: "Nykvarn" },
  { label: "Nyköping", value: "Nyköping" },
  { label: "Nynäshamn", value: "Nynäshamn" },
  { label: "Nås", value: "Nås" },
  { label: "Ockelbo", value: "Ockelbo" },
  { label: "Olofström", value: "Olofström" },
  { label: "Orsa", value: "Orsa" },
  { label: "Orust", value: "Orust" },
  { label: "Osby", value: "Osby" },
  { label: "Oskarshamn", value: "Oskarshamn" },
  { label: "Ovanåker", value: "Ovanåker" },
  { label: "Oxelösund", value: "Oxelösund" },
  { label: "Pajala", value: "Pajala" },
  { label: "Partille", value: "Partille" },
  { label: "Perstorp", value: "Perstorp" },
  { label: "Piteå", value: "Piteå" },
  { label: "Ragunda", value: "Ragunda" },
  { label: "Robertsfors", value: "Robertsfors" },
  { label: "Ronneby", value: "Ronneby" },
  { label: "Rättvik", value: "Rättvik" },
  { label: "Sala", value: "Sala" },
  { label: "Salem", value: "Salem" },
  { label: "Sandviken", value: "Sandviken" },
  { label: "Sigtuna", value: "Sigtuna" },
  { label: "Simrishamn", value: "Simrishamn" },
  { label: "Sjöbo", value: "Sjöbo" },
  { label: "Skara", value: "Skara" },
  { label: "Skellefteå", value: "Skellefteå" },
  { label: "Skinnskatteberg", value: "Skinnskatteberg" },
  { label: "Skurup", value: "Skurup" },
  { label: "Skövde", value: "Skövde" },
  { label: "Smedjebacken", value: "Smedjebacken" },
  { label: "Sollefteå", value: "Sollefteå" },
  { label: "Sollentuna", value: "Sollentuna" },
  { label: "Solna", value: "Solna" },
  { label: "Sorsele", value: "Sorsele" },
  { label: "Sotenäs", value: "Sotenäs" },
  { label: "Staffanstorp", value: "Staffanstorp" },
  { label: "Stenungsund", value: "Stenungsund" },
  { label: "Stockholm", value: "Stockholm" },
  { label: "Storfors", value: "Storfors" },
  { label: "Storuman", value: "Storuman" },
  { label: "Strängnäs", value: "Strängnäs" },
  { label: "Strömstad", value: "Strömstad" },
  { label: "Strömsund", value: "Strömsund" },
  { label: "Sundbyberg", value: "Sundbyberg" },
  { label: "Sundsvall", value: "Sundsvall" },
  { label: "Sunne", value: "Sunne" },
  { label: "Surahammar", value: "Surahammar" },
  { label: "Svalöv", value: "Svalöv" },
  { label: "Svedala", value: "Svedala" },
  { label: "Svenljunga", value: "Svenljunga" },
  { label: "Säffle", value: "Säffle" },
  { label: "Säter", value: "Säter" },
  { label: "Sävsjö", value: "Sävsjö" },
  { label: "Söderhamn", value: "Söderhamn" },
  { label: "Söderköping", value: "Söderköping" },
  { label: "Södertälje", value: "Södertälje" },
  { label: "Sölvesborg", value: "Sölvesborg" },
  { label: "Tanum", value: "Tanum" },
  { label: "Tibro", value: "Tibro" },
  { label: "Tidaholm", value: "Tidaholm" },
  { label: "Tierp", value: "Tierp" },
  { label: "Timrå", value: "Timrå" },
  { label: "Tingsryd", value: "Tingsryd" },
  { label: "Tjörn", value: "Tjörn" },
  { label: "Tomelilla", value: "Tomelilla" },
  { label: "Torsby", value: "Torsby" },
  { label: "Torsås", value: "Torsås" },
  { label: "Tranemo", value: "Tranemo" },
  { label: "Tranås", value: "Tranås" },
  { label: "Trelleborg", value: "Trelleborg" },
  { label: "Trollhättan", value: "Trollhättan" },
  { label: "Trosa", value: "Trosa" },
  { label: "Tyresö", value: "Tyresö" },
  { label: "Täby", value: "Täby" },
  { label: "Töreboda", value: "Töreboda" },
  { label: "Uddevalla", value: "Uddevalla" },
  { label: "Ulricehamn", value: "Ulricehamn" },
  { label: "Umeå", value: "Umeå" },
  { label: "Upplands-Bro", value: "Upplands-Bro" },
  { label: "Upplands-Väsby", value: "Upplands-Väsby" },
  { label: "Uppsala", value: "Uppsala" },
  { label: "Uppvidinge", value: "Uppvidinge" },
  { label: "Vadstena", value: "Vadstena" },
  { label: "Vaggeryd", value: "Vaggeryd" },
  { label: "Valdemarsvik", value: "Valdemarsvik" },
  { label: "Vallentuna", value: "Vallentuna" },
  { label: "Vansbro", value: "Vansbro" },
  { label: "Vara", value: "Vara" },
  { label: "Varberg", value: "Varberg" },
  { label: "Vaxholm", value: "Vaxholm" },
  { label: "Vellinge", value: "Vellinge" },
  { label: "Vetlanda", value: "Vetlanda" },
  { label: "Vilhelmina", value: "Vilhelmina" },
  { label: "Vimmerby", value: "Vimmerby" },
  { label: "Vindeln", value: "Vindeln" },
  { label: "Vingåker", value: "Vingåker" },
  { label: "Vårgårda", value: "Vårgårda" },
  { label: "Vänersborg", value: "Vänersborg" },
  { label: "Vännäs", value: "Vännäs" },
  { label: "Värmdö", value: "Värmdö" },
  { label: "Värnamo", value: "Värnamo" },
  { label: "Västervik", value: "Västervik" },
  { label: "Västerås", value: "Västerås" },
  { label: "Växjö", value: "Växjö" },
  { label: "Ydre", value: "Ydre" },
  { label: "Ystad", value: "Ystad" },
  { label: "Åmål", value: "Åmål" },
  { label: "Ånge", value: "Ånge" },
  { label: "Åre", value: "Åre" },
  { label: "Årjäng", value: "Årjäng" },
  { label: "Åsele", value: "Åsele" },
  { label: "Åstorp", value: "Åstorp" },
  { label: "Åtvidaberg", value: "Åtvidaberg" },
  { label: "Älmhult", value: "Älmhult" },
  { label: "Älvdalen", value: "Älvdalen" },
  { label: "Älvkarleby", value: "Älvkarleby" },
  { label: "Älvsbyn", value: "Älvsbyn" },
  { label: "Ängelholm", value: "Ängelholm" },
  { label: "Öckerö", value: "Öckerö" },
  { label: "Ödeshög", value: "Ödeshög" },
  { label: "Örebro", value: "Örebro" },
  { label: "Örkelljunga", value: "Örkelljunga" },
  { label: "Örnsköldsvik", value: "Örnsköldsvik" },
  { label: "Östersund", value: "Östersund" },
  { label: "Österåker", value: "Österåker" },
  { label: "Östhammar", value: "Östhammar" },
];

export const regionOptions = [
  { label: "Blekinge", value: "Blekinge" },
  { label: "Dalarna", value: "Dalarna" },
  { label: "Gotland", value: "Gotland" },
  { label: "Gävleborg", value: "Gävleborg" },
  { label: "Halland", value: "Halland" },
  { label: "Jämtland", value: "Jämtland" },
  { label: "Jönköping", value: "Jönköping" },
  { label: "Kalmar", value: "Kalmar" },
  { label: "Kronoberg", value: "Kronoberg" },
  { label: "Norrbotten", value: "Norrbotten" },
  { label: "Skåne", value: "Skåne" },
  { label: "Stockholm", value: "Stockholm" },
  { label: "Södermanland", value: "Södermanland" },
  { label: "Uppsala", value: "Uppsala" },
  { label: "Värmland", value: "Värmland" },
  { label: "Västerbotten", value: "Västerbotten" },
  { label: "Västernorrland", value: "Västernorrland" },
  { label: "Västmanland", value: "Västmanland" },
  { label: "Västra Götaland", value: "Västra Götaland" },
  { label: "Örebro", value: "Örebro" },
  { label: "Östergötland", value: "Östergötland" },
];
export const lansAndKommunes = {
  Blekinge: ["Karlshamn", "Karlskrona", "Olofström", "Ronneby", "Sölvesborg"],
  Dalarna: [
    "Avesta",
    "Borlänge",
    "Falun",
    "Gagnef",
    "Hedemora",
    "Leksand",
    "Ludvika",
    "Malung-Sälen",
    "Mora",
    "Orsa",
    "Rättvik",
    "Smedjebacken",
    "Säter",
    "Vansbro",
    "Älvdalen",
  ],
  Gotland: ["Gotland"],
  Gävleborg: [
    "Bollnäs",
    "Gävle",
    "Hofors",
    "Hudiksvall",
    "Ljusdal",
    "Nordanstig",
    "Ockelbo",
    "Ovanåker",
    "Sandviken",
    "Söderhamn",
  ],
  Halland: [
    "Falkenberg",
    "Halmstad",
    "Hylte",
    "Kungsbacka",
    "Laholm",
    "Varberg",
  ],
  Jämtland: [
    "Berg",
    "Bräcke",
    "Härjedalen",
    "Krokom",
    "Ragunda",
    "Strömsund",
    "Åre",
    "Östersund",
  ],
  Jönköping: [
    "Aneby",
    "Eksjö",
    "Gislaved",
    "Gnosjö",
    "Habo",
    "Jönköping",
    "Mullsjö",
    "Nässjö",
    "Sävsjö",
    "Tranås",
    "Vaggeryd",
    "Vetlanda",
    "Värnamo",
  ],
  Kalmar: [
    "Borgholm",
    "Emmaboda",
    "Hultsfred",
    "Högsby",
    "Kalmar",
    "Mönsterås",
    "Mörbylånga",
    "Nybro",
    "Oskarshamn",
    "Torsås",
    "Vimmerby",
    "Västervik",
  ],
  Kronoberg: [
    "Alvesta",
    "Lessebo",
    "Ljungby",
    "Markaryd",
    "Tingsryd",
    "Uppvidinge",
    "Växjö",
    "Älmhult",
  ],
  Norrbotten: [
    "Arjeplog",
    "Arvidsjaur",
    "Boden",
    "Gällivare",
    "Haparanda",
    "Jokkmokk",
    "Kalix",
    "Kiruna",
    "Luleå",
    "Pajala",
    "Piteå",
    "Älvsbyn",
    "Överkalix",
    "Övertorneå",
  ],
  Skåne: [
    "Bjuv",
    "Bromölla",
    "Burlöv",
    "Båstad",
    "Eslöv",
    "Helsingborg",
    "Hässleholm",
    "Höganäs",
    "Hörby",
    "Höör",
    "Klippan",
    "Kristianstad",
    "Kävlinge",
    "Landskrona",
    "Lomma",
    "Lund",
    "Malmö",
    "Osby",
    "Perstorp",
    "Simrishamn",
    "Sjöbo",
    "Skurup",
    "Staffanstorp",
    "Svalöv",
    "Svedala",
    "Tomelilla",
    "Trelleborg",
    "Vellinge",
    "Ystad",
    "Åstorp",
    "Ängelholm",
    "Örkelljunga",
    "Östra Göinge",
  ],
  Stockholm: [
    "Botkyrka",
    "Danderyd",
    "Ekerö",
    "Haninge",
    "Huddinge",
    "Järfälla",
    "Lidingö",
    "Nacka",
    "Norrtälje",
    "Nykvarn",
    "Nynäshamn",
    "Salem",
    "Sigtuna",
    "Sollentuna",
    "Solna",
    "Stockholm",
    "Sundbyberg",
    "Södertälje",
    "Tyresö",
    "Täby",
    "Upplands-Bro",
    "Upplands Väsby",
    "Vallentuna",
    "Vaxholm",
    "Värmdö",
    "Österåker",
  ],
  Södermanland: [
    "Eskilstuna",
    "Flen",
    "Gnesta",
    "Katrineholm",
    "Nyköping",
    "Oxelösund",
    "Strängnäs",
    "Trosa",
    "Vingåker",
  ],
  Uppsala: [
    "Enköping",
    "Heby",
    "Håbo",
    "Knivsta",
    "Tierp",
    "Uppsala",
    "Älvkarleby",
    "Östhammar",
  ],
  Värmland: [
    "Arvika",
    "Eda",
    "Filipstad",
    "Forshaga",
    "Grums",
    "Hagfors",
    "Hammarö",
    "Karlstad",
    "Kil",
    "Kristinehamn",
    "Munkfors",
    "Storfors",
    "Sunne",
    "Säffle",
    "Torsby",
    "Årjäng",
  ],
  Västerbotten: [
    "Bjurholm",
    "Dorotea",
    "Lycksele",
    "Malå",
    "Nordmaling",
    "Norsjö",
    "Robertsfors",
    "Skellefteå",
    "Sorsele",
    "Storuman",
    "Umeå",
    "Vilhelmina",
    "Vindeln",
    "Vännäs",
    "Åsele",
  ],
  Västernorrland: [
    "Härnösand",
    "Kramfors",
    "Sollefteå",
    "Sundsvall",
    "Timrå",
    "Ånge",
    "Örnsköldsvik",
  ],
  Västmanland: [
    "Arboga",
    "Fagersta",
    "Hallstahammar",
    "Kungsör",
    "Köping",
    "Norberg",
    "Sala",
    "Skinnskatteberg",
    "Surahammar",
    "Västerås",
  ],
  "Västra Götaland": [
    "Ale",
    "Alingsås",
    "Bengtsfors",
    "Bollebygd",
    "Borås",
    "Dals-Ed",
    "Essunga",
    "Falköping",
    "Färgelanda",
    "Grästorp",
    "Gullspång",
    "Göteborg",
    "Götene",
    "Herrljunga",
    "Hjo",
    "Härryda",
    "Karlsborg",
    "Kungälv",
    "Lerum",
    "Lidköping",
    "Lilla Edet",
    "Lysekil",
    "Mariestad",
    "Mark",
    "Mellerud",
    "Munkedal",
    "Mölndal",
    "Orust",
    "Partille",
    "Skara",
    "Skövde",
    "Sotenäs",
    "Stenungsund",
    "Strömstad",
    "Svenljunga",
    "Tanum",
    "Tibro",
    "Tidaholm",
    "Tjörn",
    "Tranemo",
    "Trollhättan",
    "Töreboda",
    "Uddevalla",
    "Ulricehamn",
    "Vara",
    "Vårgårda",
    "Vänersborg",
    "Åmål",
    "Öckerö",
  ],
  Örebro: [
    "Askersund",
    "Degerfors",
    "Hallsberg",
    "Hällefors",
    "Karlskoga",
    "Kumla",
    "Laxå",
    "Lekeberg",
    "Lindesberg",
    "Ljusnarsberg",
    "Nora",
    "Örebro",
  ],
  Östergötland: [
    "Boxholm",
    "Finspång",
    "Kinda",
    "Linköping",
    "Mjölby",
    "Motala",
    "Norrköping",
    "Söderköping",
    "Vadstena",
    "Valdemarsvik",
    "Ydre",
    "Åtvidaberg",
    "Ödeshög",
  ],
};

export const countriesWithPhoneCodes = [
  {
    code: "+7 840",
    name: "Abkhazia",
  },
  {
    code: "+93",
    name: "Afghanistan",
  },
  {
    code: "+355",
    name: "Albania",
  },
  {
    code: "+213",
    name: "Algeria",
  },
  {
    code: "+1 684",
    name: "American Samoa",
  },
  {
    code: "+376",
    name: "Andorra",
  },
  {
    code: "+244",
    name: "Angola",
  },
  {
    code: "+1 264",
    name: "Anguilla",
  },
  {
    code: "+1 268",
    name: "Antigua and Barbuda",
  },
  {
    code: "+54",
    name: "Argentina",
  },
  {
    code: "+374",
    name: "Armenia",
  },
  {
    code: "+297",
    name: "Aruba",
  },
  {
    code: "+247",
    name: "Ascension",
  },
  {
    code: "+61",
    name: "Australia",
  },
  {
    code: "+672",
    name: "Australian External Territories",
  },
  {
    code: "+43",
    name: "Austria",
  },
  {
    code: "+994",
    name: "Azerbaijan",
  },
  {
    code: "+1 242",
    name: "Bahamas",
  },
  {
    code: "+973",
    name: "Bahrain",
  },
  {
    code: "+880",
    name: "Bangladesh",
  },
  {
    code: "+1 246",
    name: "Barbados",
  },
  {
    code: "+1 268",
    name: "Barbuda",
  },
  {
    code: "+375",
    name: "Belarus",
  },
  {
    code: "+32",
    name: "Belgium",
  },
  {
    code: "+501",
    name: "Belize",
  },
  {
    code: "+229",
    name: "Benin",
  },
  {
    code: "+1 441",
    name: "Bermuda",
  },
  {
    code: "+975",
    name: "Bhutan",
  },
  {
    code: "+591",
    name: "Bolivia",
  },
  {
    code: "+387",
    name: "Bosnia and Herzegovina",
  },
  {
    code: "+267",
    name: "Botswana",
  },
  {
    code: "+55",
    name: "Brazil",
  },
  {
    code: "+246",
    name: "British Indian Ocean Territory",
  },
  {
    code: "+1 284",
    name: "British Virgin Islands",
  },
  {
    code: "+673",
    name: "Brunei",
  },
  {
    code: "+359",
    name: "Bulgaria",
  },
  {
    code: "+226",
    name: "Burkina Faso",
  },
  {
    code: "+257",
    name: "Burundi",
  },
  {
    code: "+855",
    name: "Cambodia",
  },
  {
    code: "+237",
    name: "Cameroon",
  },
  {
    code: "+1",
    name: "Canada",
  },
  {
    code: "+238",
    name: "Cape Verde",
  },
  {
    code: "+ 345",
    name: "Cayman Islands",
  },
  {
    code: "+236",
    name: "Central African Republic",
  },
  {
    code: "+235",
    name: "Chad",
  },
  {
    code: "+56",
    name: "Chile",
  },
  {
    code: "+86",
    name: "China",
  },
  {
    code: "+61",
    name: "Christmas Island",
  },
  {
    code: "+61",
    name: "Cocos-Keeling Islands",
  },
  {
    code: "+57",
    name: "Colombia",
  },
  {
    code: "+269",
    name: "Comoros",
  },
  {
    code: "+242",
    name: "Congo",
  },
  {
    code: "+243",
    name: "Congo, Dem. Rep. of (Zaire)",
  },
  {
    code: "+682",
    name: "Cook Islands",
  },
  {
    code: "+506",
    name: "Costa Rica",
  },
  {
    code: "+385",
    name: "Croatia",
  },
  {
    code: "+53",
    name: "Cuba",
  },
  {
    code: "+599",
    name: "Curacao",
  },
  {
    code: "+537",
    name: "Cyprus",
  },
  {
    code: "+420",
    name: "Czech Republic",
  },
  {
    code: "+45",
    name: "Denmark",
  },
  {
    code: "+246",
    name: "Diego Garcia",
  },
  {
    code: "+253",
    name: "Djibouti",
  },
  {
    code: "+1 767",
    name: "Dominica",
  },
  {
    code: "+1 809",
    name: "Dominican Republic",
  },
  {
    code: "+670",
    name: "East Timor",
  },
  {
    code: "+56",
    name: "Easter Island",
  },
  {
    code: "+593",
    name: "Ecuador",
  },
  {
    code: "+20",
    name: "Egypt",
  },
  {
    code: "+503",
    name: "El Salvador",
  },
  {
    code: "+240",
    name: "Equatorial Guinea",
  },
  {
    code: "+291",
    name: "Eritrea",
  },
  {
    code: "+372",
    name: "Estonia",
  },
  {
    code: "+251",
    name: "Ethiopia",
  },
  {
    code: "+500",
    name: "Falkland Islands",
  },
  {
    code: "+298",
    name: "Faroe Islands",
  },
  {
    code: "+679",
    name: "Fiji",
  },
  {
    code: "+358",
    name: "Finland",
  },
  {
    code: "+33",
    name: "France",
  },
  {
    code: "+596",
    name: "French Antilles",
  },
  {
    code: "+594",
    name: "French Guiana",
  },
  {
    code: "+689",
    name: "French Polynesia",
  },
  {
    code: "+241",
    name: "Gabon",
  },
  {
    code: "+220",
    name: "Gambia",
  },
  {
    code: "+995",
    name: "Georgia",
  },
  {
    code: "+49",
    name: "Germany",
  },
  {
    code: "+233",
    name: "Ghana",
  },
  {
    code: "+350",
    name: "Gibraltar",
  },
  {
    code: "+30",
    name: "Greece",
  },
  {
    code: "+299",
    name: "Greenland",
  },
  {
    code: "+1 473",
    name: "Grenada",
  },
  {
    code: "+590",
    name: "Guadeloupe",
  },
  {
    code: "+1 671",
    name: "Guam",
  },
  {
    code: "+502",
    name: "Guatemala",
  },
  {
    code: "+224",
    name: "Guinea",
  },
  {
    code: "+245",
    name: "Guinea-Bissau",
  },
  {
    code: "+595",
    name: "Guyana",
  },
  {
    code: "+509",
    name: "Haiti",
  },
  {
    code: "+504",
    name: "Honduras",
  },
  {
    code: "+852",
    name: "Hong Kong SAR China",
  },
  {
    code: "+36",
    name: "Hungary",
  },
  {
    code: "+354",
    name: "Iceland",
  },
  {
    code: "+91",
    name: "India",
  },
  {
    code: "+62",
    name: "Indonesia",
  },
  {
    code: "+98",
    name: "Iran",
  },
  {
    code: "+964",
    name: "Iraq",
  },
  {
    code: "+353",
    name: "Ireland",
  },
  {
    code: "+972",
    name: "Israel",
  },
  {
    code: "+39",
    name: "Italy",
  },
  {
    code: "+225",
    name: "Ivory Coast",
  },
  {
    code: "+1 876",
    name: "Jamaica",
  },
  {
    code: "+81",
    name: "Japan",
  },
  {
    code: "+962",
    name: "Jordan",
  },
  {
    code: "+7 7",
    name: "Kazakhstan",
  },
  {
    code: "+254",
    name: "Kenya",
  },
  {
    code: "+686",
    name: "Kiribati",
  },
  {
    code: "+965",
    name: "Kuwait",
  },
  {
    code: "+996",
    name: "Kyrgyzstan",
  },
  {
    code: "+856",
    name: "Laos",
  },
  {
    code: "+371",
    name: "Latvia",
  },
  {
    code: "+961",
    name: "Lebanon",
  },
  {
    code: "+266",
    name: "Lesotho",
  },
  {
    code: "+231",
    name: "Liberia",
  },
  {
    code: "+218",
    name: "Libya",
  },
  {
    code: "+423",
    name: "Liechtenstein",
  },
  {
    code: "+370",
    name: "Lithuania",
  },
  {
    code: "+352",
    name: "Luxembourg",
  },
  {
    code: "+853",
    name: "Macau SAR China",
  },
  {
    code: "+389",
    name: "Macedonia",
  },
  {
    code: "+261",
    name: "Madagascar",
  },
  {
    code: "+265",
    name: "Malawi",
  },
  {
    code: "+60",
    name: "Malaysia",
  },
  {
    code: "+960",
    name: "Maldives",
  },
  {
    code: "+223",
    name: "Mali",
  },
  {
    code: "+356",
    name: "Malta",
  },
  {
    code: "+692",
    name: "Marshall Islands",
  },
  {
    code: "+596",
    name: "Martinique",
  },
  {
    code: "+222",
    name: "Mauritania",
  },
  {
    code: "+230",
    name: "Mauritius",
  },
  {
    code: "+262",
    name: "Mayotte",
  },
  {
    code: "+52",
    name: "Mexico",
  },
  {
    code: "+691",
    name: "Micronesia",
  },
  {
    code: "+1 808",
    name: "Midway Island",
  },
  {
    code: "+373",
    name: "Moldova",
  },
  {
    code: "+377",
    name: "Monaco",
  },
  {
    code: "+976",
    name: "Mongolia",
  },
  {
    code: "+382",
    name: "Montenegro",
  },
  {
    code: "+1664",
    name: "Montserrat",
  },
  {
    code: "+212",
    name: "Morocco",
  },
  {
    code: "+95",
    name: "Myanmar",
  },
  {
    code: "+264",
    name: "Namibia",
  },
  {
    code: "+674",
    name: "Nauru",
  },
  {
    code: "+977",
    name: "Nepal",
  },
  {
    code: "+31",
    name: "Netherlands",
  },
  {
    code: "+599",
    name: "Netherlands Antilles",
  },
  {
    code: "+1 869",
    name: "Nevis",
  },
  {
    code: "+687",
    name: "New Caledonia",
  },
  {
    code: "+64",
    name: "New Zealand",
  },
  {
    code: "+505",
    name: "Nicaragua",
  },
  {
    code: "+227",
    name: "Niger",
  },
  {
    code: "+234",
    name: "Nigeria",
  },
  {
    code: "+683",
    name: "Niue",
  },
  {
    code: "+672",
    name: "Norfolk Island",
  },
  {
    code: "+850",
    name: "North Korea",
  },
  {
    code: "+1 670",
    name: "Northern Mariana Islands",
  },
  {
    code: "+47",
    name: "Norway",
  },
  {
    code: "+968",
    name: "Oman",
  },
  {
    code: "+92",
    name: "Pakistan",
  },
  {
    code: "+680",
    name: "Palau",
  },
  {
    code: "+970",
    name: "Palestinian Territory",
  },
  {
    code: "+507",
    name: "Panama",
  },
  {
    code: "+675",
    name: "Papua New Guinea",
  },
  {
    code: "+595",
    name: "Paraguay",
  },
  {
    code: "+51",
    name: "Peru",
  },
  {
    code: "+63",
    name: "Philippines",
  },
  {
    code: "+48",
    name: "Poland",
  },
  {
    code: "+351",
    name: "Portugal",
  },
  {
    code: "+1 787",
    name: "Puerto Rico",
  },
  {
    code: "+974",
    name: "Qatar",
  },
  {
    code: "+262",
    name: "Reunion",
  },
  {
    code: "+40",
    name: "Romania",
  },
  {
    code: "+7",
    name: "Russia",
  },
  {
    code: "+250",
    name: "Rwanda",
  },
  {
    code: "+685",
    name: "Samoa",
  },
  {
    code: "+378",
    name: "San Marino",
  },
  {
    code: "+966",
    name: "Saudi Arabia",
  },
  {
    code: "+221",
    name: "Senegal",
  },
  {
    code: "+381",
    name: "Serbia",
  },
  {
    code: "+248",
    name: "Seychelles",
  },
  {
    code: "+232",
    name: "Sierra Leone",
  },
  {
    code: "+65",
    name: "Singapore",
  },
  {
    code: "+421",
    name: "Slovakia",
  },
  {
    code: "+386",
    name: "Slovenia",
  },
  {
    code: "+677",
    name: "Solomon Islands",
  },
  {
    code: "+27",
    name: "South Africa",
  },
  {
    code: "+500",
    name: "South Georgia and the South Sandwich Islands",
  },
  {
    code: "+82",
    name: "South Korea",
  },
  {
    code: "+34",
    name: "Spain",
  },
  {
    code: "+94",
    name: "Sri Lanka",
  },
  {
    code: "+249",
    name: "Sudan",
  },
  {
    code: "+597",
    name: "Suriname",
  },
  {
    code: "+268",
    name: "Swaziland",
  },
  {
    code: "+46",
    name: "Sweden",
  },
  {
    code: "+41",
    name: "Switzerland",
  },
  {
    code: "+963",
    name: "Syria",
  },
  {
    code: "+886",
    name: "Taiwan",
  },
  {
    code: "+992",
    name: "Tajikistan",
  },
  {
    code: "+255",
    name: "Tanzania",
  },
  {
    code: "+66",
    name: "Thailand",
  },
  {
    code: "+670",
    name: "Timor Leste",
  },
  {
    code: "+228",
    name: "Togo",
  },
  {
    code: "+690",
    name: "Tokelau",
  },
  {
    code: "+676",
    name: "Tonga",
  },
  {
    code: "+1 868",
    name: "Trinidad and Tobago",
  },
  {
    code: "+216",
    name: "Tunisia",
  },
  {
    code: "+90",
    name: "Turkey",
  },
  {
    code: "+993",
    name: "Turkmenistan",
  },
  {
    code: "+1 649",
    name: "Turks and Caicos Islands",
  },
  {
    code: "+688",
    name: "Tuvalu",
  },
  {
    code: "+1 340",
    name: "U.S. Virgin Islands",
  },
  {
    code: "+256",
    name: "Uganda",
  },
  {
    code: "+380",
    name: "Ukraine",
  },
  {
    code: "+971",
    name: "United Arab Emirates",
  },
  {
    code: "+44",
    name: "United Kingdom",
  },
  {
    code: "+1",
    name: "United States",
  },
  {
    code: "+598",
    name: "Uruguay",
  },
  {
    code: "+998",
    name: "Uzbekistan",
  },
  {
    code: "+678",
    name: "Vanuatu",
  },
  {
    code: "+58",
    name: "Venezuela",
  },
  {
    code: "+84",
    name: "Vietnam",
  },
  {
    code: "+1 808",
    name: "Wake Island",
  },
  {
    code: "+681",
    name: "Wallis and Futuna",
  },
  {
    code: "+967",
    name: "Yemen",
  },
  {
    code: "+260",
    name: "Zambia",
  },
  {
    code: "+255",
    name: "Zanzibar",
  },
  {
    code: "+263",
    name: "Zimbabwe",
  },
];
